// <auto-generated>
// Rewired Constants
// This list was generated on 1/26/2019 5:22:11 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace InputConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int LookHorizontal = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int LookVertical = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int Walk = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int Strafe = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Action0")]
        public const int Interact = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Start")]
        public const int Start = 5;
		[Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Select")]
        public const int Select = 6;
    }
}
